import { Prisma, PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const initialProducts:Prisma.ProductCreateManyInput[] =[
    {
      nameEn: "Voltaren Emulgel #1",
      nameAr: "فولتارين إمولجيل رقم 1",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 100,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_1.jpg",
    },
    {
      nameEn: "Augmentin 1g #2",
      nameAr: "أوجمنتين ١جم رقم 2",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 100,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_2.jpg",
    },
    {
      nameEn: "Zyrtec 10mg #3",
      nameAr: "زيرتك 10 مجم رقم 3",
      descriptionEN: "Zyrtec 10mg is an antihistamine used to treat allergy symptoms such as sneezing, runny nose, and itchy or watery eyes.",
      descriptionAr: "زيرتك 10 مجم هو مضاد للهستامين يُستخدم لعلاج أعراض الحساسية مثل العطس، وسيلان الأنف، والحكة أو العيون الدامعة.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 92,
      titleEn: "Zyrtec 10mg Title",
      titleAr: "عنوان زيرتك 10 مجم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_3.jpg",
    },
    {
      nameEn: "Augmentin 1g #4",
      nameAr: "أوجمنتين ١جم رقم 4",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 74,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_4.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #5",
      nameAr: "فولتارين إمولجيل رقم 5",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 22,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_5.jpg",
    },
    {
      nameEn: "Amoxil #6",
      nameAr: "أموكسيل رقم 6",
      descriptionEN: "Amoxil is a penicillin-type antibiotic used to treat a wide variety of bacterial infections, such as ear infections and pneumonia.",
      descriptionAr: "أموكسيل هو مضاد حيوي من نوع البنسلين يُستخدم لعلاج مجموعة متنوعة من العدوى البكتيرية، مثل التهابات الأذن والالتهاب الرئوي.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 63,
      titleEn: "Amoxil Title",
      titleAr: "عنوان أموكسيل",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_6.jpg",
    },
    {
      nameEn: "Paracetamol #7",
      nameAr: "باراسيتامول رقم 7",
      descriptionEN: "Paracetamol is a common painkiller used to treat aches, pains, and reduce fever. It is often used for headaches and cold symptoms.",
      descriptionAr: "الباراسيتامول هو مسكن شائع يُستخدم لعلاج الآلام والحمى. يُستخدم غالبًا لعلاج الصداع وأعراض البرد.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 96,
      titleEn: "Paracetamol Title",
      titleAr: "عنوان باراسيتامول",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_7.jpg",
    },
    {
      nameEn: "Nexium 40mg #8",
      nameAr: "نيكسيوم ٤٠ مجم رقم 8",
      descriptionEN: "Nexium 40mg reduces stomach acid and is used to treat gastroesophageal reflux disease (GERD) and other acid-related conditions.",
      descriptionAr: "نيكسيوم 40 مجم يقلل من حموضة المعدة ويُستخدم لعلاج الارتجاع المعدي المريئي (GERD) وحالات أخرى متعلقة بالحموضة.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 42,
      titleEn: "Nexium 40mg Title",
      titleAr: "عنوان نيكسيوم ٤٠ مجم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_8.jpg",
    },
    {
      nameEn: "Panadol Extra #9",
      nameAr: "بانادول إكسترا رقم 9",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 57,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_9.jpg",
    },
    {
      nameEn: "Nexium 40mg #10",
      nameAr: "نيكسيوم ٤٠ مجم رقم 10",
      descriptionEN: "Nexium 40mg reduces stomach acid and is used to treat gastroesophageal reflux disease (GERD) and other acid-related conditions.",
      descriptionAr: "نيكسيوم 40 مجم يقلل من حموضة المعدة ويُستخدم لعلاج الارتجاع المعدي المريئي (GERD) وحالات أخرى متعلقة بالحموضة.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 53,
      titleEn: "Nexium 40mg Title",
      titleAr: "عنوان نيكسيوم ٤٠ مجم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_10.jpg",
    },
    {
      nameEn: "Zyrtec 10mg #11",
      nameAr: "زيرتك 10 مجم رقم 11",
      descriptionEN: "Zyrtec 10mg is an antihistamine used to treat allergy symptoms such as sneezing, runny nose, and itchy or watery eyes.",
      descriptionAr: "زيرتك 10 مجم هو مضاد للهستامين يُستخدم لعلاج أعراض الحساسية مثل العطس، وسيلان الأنف، والحكة أو العيون الدامعة.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 95,
      titleEn: "Zyrtec 10mg Title",
      titleAr: "عنوان زيرتك 10 مجم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_11.jpg",
    },
    {
      nameEn: "Betadine Mouthwash #12",
      nameAr: "بيتادين غسول فم رقم 12",
      descriptionEN: "Betadine Mouthwash is an antiseptic solution that helps reduce oral germs and prevent infections of the mouth and throat.",
      descriptionAr: "غسول الفم بيتادين هو محلول مطهر يساعد في تقليل الجراثيم الفموية والوقاية من التهابات الفم والحلق.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 93,
      titleEn: "Betadine Mouthwash Title",
      titleAr: "عنوان بيتادين غسول فم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_12.jpg",
    },
    {
      nameEn: "Panadol Extra #13",
      nameAr: "بانادول إكسترا رقم 13",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 64,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_13.jpg",
    },
    {
      nameEn: "Augmentin 1g #14",
      nameAr: "أوجمنتين ١جم رقم 14",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 60,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_14.jpg",
    },
    {
      nameEn: "Augmentin 1g #15",
      nameAr: "أوجمنتين ١جم رقم 15",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 71,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_15.jpg",
    },
    {
      nameEn: "Betadine Mouthwash #16",
      nameAr: "بيتادين غسول فم رقم 16",
      descriptionEN: "Betadine Mouthwash is an antiseptic solution that helps reduce oral germs and prevent infections of the mouth and throat.",
      descriptionAr: "غسول الفم بيتادين هو محلول مطهر يساعد في تقليل الجراثيم الفموية والوقاية من التهابات الفم والحلق.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 46,
      titleEn: "Betadine Mouthwash Title",
      titleAr: "عنوان بيتادين غسول فم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_16.jpg",
    },
    {
      nameEn: "Panadol Extra #17",
      nameAr: "بانادول إكسترا رقم 17",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 20,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: false,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_17.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #18",
      nameAr: "فولتارين إمولجيل رقم 18",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 78,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_18.jpg",
    },
    {
      nameEn: "Nexium 40mg #19",
      nameAr: "نيكسيوم ٤٠ مجم رقم 19",
      descriptionEN: "Nexium 40mg reduces stomach acid and is used to treat gastroesophageal reflux disease (GERD) and other acid-related conditions.",
      descriptionAr: "نيكسيوم 40 مجم يقلل من حموضة المعدة ويُستخدم لعلاج الارتجاع المعدي المريئي (GERD) وحالات أخرى متعلقة بالحموضة.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 71,
      titleEn: "Nexium 40mg Title",
      titleAr: "عنوان نيكسيوم ٤٠ مجم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_19.jpg",
    },
    {
      nameEn: "Dulcolax Tablets #20",
      nameAr: "دلكولاكس أقراص رقم 20",
      descriptionEN: "Dulcolax Tablets are a stimulant laxative used to treat occasional constipation and to clean the intestines before a bowel examination.",
      descriptionAr: "أقراص دلكولاكس هي ملين منبه يُستخدم لعلاج الإمساك العرضي وتنظيف الأمعاء قبل الفحوصات.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 40,
      titleEn: "Dulcolax Tablets Title",
      titleAr: "عنوان دلكولاكس أقراص",
      isFav: false,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_20.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #21",
      nameAr: "فولتارين إمولجيل رقم 21",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 56,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_21.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #22",
      nameAr: "فولتارين إمولجيل رقم 22",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 37,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: false,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_22.jpg",
    },
    {
      nameEn: "Brufen 400mg #23",
      nameAr: "بروفين ٤٠٠ مجم رقم 23",
      descriptionEN: "Brufen 400mg is an anti-inflammatory painkiller used for mild to moderate pain, inflammation, and fever.",
      descriptionAr: "بروفين 400 مجم هو مسكن مضاد للالتهاب يُستخدم لتسكين الآلام الخفيفة إلى المتوسطة، والالتهابات، وخفض الحمى.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 81,
      titleEn: "Brufen 400mg Title",
      titleAr: "عنوان بروفين ٤٠٠ مجم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_23.jpg",
    },
    {
      nameEn: "Augmentin 1g #24",
      nameAr: "أوجمنتين ١جم رقم 24",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 82,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_24.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #25",
      nameAr: "فولتارين إمولجيل رقم 25",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 55,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: false,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_25.jpg",
    },
    {
      nameEn: "Paracetamol #26",
      nameAr: "باراسيتامول رقم 26",
      descriptionEN: "Paracetamol is a common painkiller used to treat aches, pains, and reduce fever. It is often used for headaches and cold symptoms.",
      descriptionAr: "الباراسيتامول هو مسكن شائع يُستخدم لعلاج الآلام والحمى. يُستخدم غالبًا لعلاج الصداع وأعراض البرد.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 24,
      titleEn: "Paracetamol Title",
      titleAr: "عنوان باراسيتامول",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_26.jpg",
    },
    {
      nameEn: "Nexium 40mg #27",
      nameAr: "نيكسيوم ٤٠ مجم رقم 27",
      descriptionEN: "Nexium 40mg reduces stomach acid and is used to treat gastroesophageal reflux disease (GERD) and other acid-related conditions.",
      descriptionAr: "نيكسيوم 40 مجم يقلل من حموضة المعدة ويُستخدم لعلاج الارتجاع المعدي المريئي (GERD) وحالات أخرى متعلقة بالحموضة.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 82,
      titleEn: "Nexium 40mg Title",
      titleAr: "عنوان نيكسيوم ٤٠ مجم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_27.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #28",
      nameAr: "فولتارين إمولجيل رقم 28",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 58,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_28.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #29",
      nameAr: "فولتارين إمولجيل رقم 29",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 79,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_29.jpg",
    },
    {
      nameEn: "Amoxil #30",
      nameAr: "أموكسيل رقم 30",
      descriptionEN: "Amoxil is a penicillin-type antibiotic used to treat a wide variety of bacterial infections, such as ear infections and pneumonia.",
      descriptionAr: "أموكسيل هو مضاد حيوي من نوع البنسلين يُستخدم لعلاج مجموعة متنوعة من العدوى البكتيرية، مثل التهابات الأذن والالتهاب الرئوي.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 80,
      titleEn: "Amoxil Title",
      titleAr: "عنوان أموكسيل",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_30.jpg",
    },
    {
      nameEn: "Dulcolax Tablets #31",
      nameAr: "دلكولاكس أقراص رقم 31",
      descriptionEN: "Dulcolax Tablets are a stimulant laxative used to treat occasional constipation and to clean the intestines before a bowel examination.",
      descriptionAr: "أقراص دلكولاكس هي ملين منبه يُستخدم لعلاج الإمساك العرضي وتنظيف الأمعاء قبل الفحوصات.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 100,
      titleEn: "Dulcolax Tablets Title",
      titleAr: "عنوان دلكولاكس أقراص",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_31.jpg",
    },
    {
      nameEn: "Panadol Extra #32",
      nameAr: "بانادول إكسترا رقم 32",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 27,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_32.jpg",
    },
    {
      nameEn: "Dulcolax Tablets #33",
      nameAr: "دلكولاكس أقراص رقم 33",
      descriptionEN: "Dulcolax Tablets are a stimulant laxative used to treat occasional constipation and to clean the intestines before a bowel examination.",
      descriptionAr: "أقراص دلكولاكس هي ملين منبه يُستخدم لعلاج الإمساك العرضي وتنظيف الأمعاء قبل الفحوصات.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 20,
      titleEn: "Dulcolax Tablets Title",
      titleAr: "عنوان دلكولاكس أقراص",
      isFav: false,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_33.jpg",
    },
    {
      nameEn: "Panadol Extra #34",
      nameAr: "بانادول إكسترا رقم 34",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 38,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_34.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #35",
      nameAr: "فولتارين إمولجيل رقم 35",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 48,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_35.jpg",
    },
    {
      nameEn: "Augmentin 1g #36",
      nameAr: "أوجمنتين ١جم رقم 36",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 70,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_36.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #37",
      nameAr: "فولتارين إمولجيل رقم 37",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 59,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_37.jpg",
    },
    {
      nameEn: "Panadol Extra #38",
      nameAr: "بانادول إكسترا رقم 38",
      descriptionEN: "Panadol Extra provides fast, effective relief from tough pain, including headache, migraine, backache, toothache, and period pain.",
      descriptionAr: "بانادول إكسترا يوفر راحة سريعة وفعالة من الآلام القوية، بما في ذلك الصداع، والصداع النصفي، وآلام الظهر، وآلام الأسنان، وآلام الدورة الشهرية.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 32,
      titleEn: "Panadol Extra Title",
      titleAr: "عنوان بانادول إكسترا",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_38.jpg",
    },
    {
      nameEn: "Paracetamol #39",
      nameAr: "باراسيتامول رقم 39",
      descriptionEN: "Paracetamol is a common painkiller used to treat aches, pains, and reduce fever. It is often used for headaches and cold symptoms.",
      descriptionAr: "الباراسيتامول هو مسكن شائع يُستخدم لعلاج الآلام والحمى. يُستخدم غالبًا لعلاج الصداع وأعراض البرد.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 27,
      titleEn: "Paracetamol Title",
      titleAr: "عنوان باراسيتامول",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_39.jpg",
    },
    {
      nameEn: "Voltaren Emulgel #40",
      nameAr: "فولتارين إمولجيل رقم 40",
      descriptionEN: "Voltaren Emulgel is a topical anti-inflammatory gel used to relieve muscle and joint pain caused by sprains, strains, and arthritis.",
      descriptionAr: "فولتارين إمولجيل هو جل مضاد للالتهاب يُستخدم لتخفيف آلام العضلات والمفاصل الناتجة عن الالتواءات والإجهاد والتهاب المفاصل.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 21,
      titleEn: "Voltaren Emulgel Title",
      titleAr: "عنوان فولتارين إمولجيل",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_40.jpg",
    },
    {
      nameEn: "Betadine Mouthwash #41",
      nameAr: "بيتادين غسول فم رقم 41",
      descriptionEN: "Betadine Mouthwash is an antiseptic solution that helps reduce oral germs and prevent infections of the mouth and throat.",
      descriptionAr: "غسول الفم بيتادين هو محلول مطهر يساعد في تقليل الجراثيم الفموية والوقاية من التهابات الفم والحلق.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 40,
      titleEn: "Betadine Mouthwash Title",
      titleAr: "عنوان بيتادين غسول فم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_41.jpg",
    },
    {
      nameEn: "Betadine Mouthwash #42",
      nameAr: "بيتادين غسول فم رقم 42",
      descriptionEN: "Betadine Mouthwash is an antiseptic solution that helps reduce oral germs and prevent infections of the mouth and throat.",
      descriptionAr: "غسول الفم بيتادين هو محلول مطهر يساعد في تقليل الجراثيم الفموية والوقاية من التهابات الفم والحلق.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 57,
      titleEn: "Betadine Mouthwash Title",
      titleAr: "عنوان بيتادين غسول فم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_42.jpg",
    },
    {
      nameEn: "Paracetamol #43",
      nameAr: "باراسيتامول رقم 43",
      descriptionEN: "Paracetamol is a common painkiller used to treat aches, pains, and reduce fever. It is often used for headaches and cold symptoms.",
      descriptionAr: "الباراسيتامول هو مسكن شائع يُستخدم لعلاج الآلام والحمى. يُستخدم غالبًا لعلاج الصداع وأعراض البرد.",
      categoryEn: "Digestive Health",
      categoryAr: "صحة الجهاز الهضمي",
      price: 24,
      titleEn: "Paracetamol Title",
      titleAr: "عنوان باراسيتامول",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_43.jpg",
    },
    {
      nameEn: "Augmentin 1g #44",
      nameAr: "أوجمنتين ١جم رقم 44",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 47,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_44.jpg",
    },
    {
      nameEn: "Zyrtec 10mg #45",
      nameAr: "زيرتك 10 مجم رقم 45",
      descriptionEN: "Zyrtec 10mg is an antihistamine used to treat allergy symptoms such as sneezing, runny nose, and itchy or watery eyes.",
      descriptionAr: "زيرتك 10 مجم هو مضاد للهستامين يُستخدم لعلاج أعراض الحساسية مثل العطس، وسيلان الأنف، والحكة أو العيون الدامعة.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 63,
      titleEn: "Zyrtec 10mg Title",
      titleAr: "عنوان زيرتك 10 مجم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_45.jpg",
    },
    {
      nameEn: "Brufen 400mg #46",
      nameAr: "بروفين ٤٠٠ مجم رقم 46",
      descriptionEN: "Brufen 400mg is an anti-inflammatory painkiller used for mild to moderate pain, inflammation, and fever.",
      descriptionAr: "بروفين 400 مجم هو مسكن مضاد للالتهاب يُستخدم لتسكين الآلام الخفيفة إلى المتوسطة، والالتهابات، وخفض الحمى.",
      categoryEn: "Antibiotics",
      categoryAr: "مضادات حيوية",
      price: 97,
      titleEn: "Brufen 400mg Title",
      titleAr: "عنوان بروفين ٤٠٠ مجم",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_46.jpg",
    },
    {
      nameEn: "Zyrtec 10mg #47",
      nameAr: "زيرتك 10 مجم رقم 47",
      descriptionEN: "Zyrtec 10mg is an antihistamine used to treat allergy symptoms such as sneezing, runny nose, and itchy or watery eyes.",
      descriptionAr: "زيرتك 10 مجم هو مضاد للهستامين يُستخدم لعلاج أعراض الحساسية مثل العطس، وسيلان الأنف، والحكة أو العيون الدامعة.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 31,
      titleEn: "Zyrtec 10mg Title",
      titleAr: "عنوان زيرتك 10 مجم",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_47.jpg",
    },
    {
      nameEn: "Amoxil #48",
      nameAr: "أموكسيل رقم 48",
      descriptionEN: "Amoxil is a penicillin-type antibiotic used to treat a wide variety of bacterial infections, such as ear infections and pneumonia.",
      descriptionAr: "أموكسيل هو مضاد حيوي من نوع البنسلين يُستخدم لعلاج مجموعة متنوعة من العدوى البكتيرية، مثل التهابات الأذن والالتهاب الرئوي.",
      categoryEn: "Pain Relief",
      categoryAr: "مسكنات",
      price: 75,
      titleEn: "Amoxil Title",
      titleAr: "عنوان أموكسيل",
      isFav: false,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 2 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_48.jpg",
    },
    {
      nameEn: "Augmentin 1g #49",
      nameAr: "أوجمنتين ١جم رقم 49",
      descriptionEN: "Augmentin 1g is a broad-spectrum antibiotic used to treat various infections caused by bacteria, such as respiratory tract infections and urinary tract infections.",
      descriptionAr: "أوجمنتين ١جم هو مضاد حيوي واسع الطيف يستخدم لعلاج مختلف أنواع العدوى البكتيرية، مثل التهابات الجهاز التنفسي والتهابات المسالك البولية.",
      categoryEn: "Allergy",
      categoryAr: "حساسية",
      price: 99,
      titleEn: "Augmentin 1g Title",
      titleAr: "عنوان أوجمنتين ١جم",
      isFav: true,
      howToUseEn: "Take 2 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_49.jpg",
    },
    {
      nameEn: "Paracetamol #50",
      nameAr: "باراسيتامول رقم 50",
      descriptionEN: "Paracetamol is a common painkiller used to treat aches, pains, and reduce fever. It is often used for headaches and cold symptoms.",
      descriptionAr: "الباراسيتامول هو مسكن شائع يُستخدم لعلاج الآلام والحمى. يُستخدم غالبًا لعلاج الصداع وأعراض البرد.",
      categoryEn: "Oral Care",
      categoryAr: "العناية بالفم",
      price: 60,
      titleEn: "Paracetamol Title",
      titleAr: "عنوان باراسيتامول",
      isFav: true,
      howToUseEn: "Take 1 tablet(s) daily after meals.",
      howToUseAr: "تناول 1 قرص يوميًا بعد الأكل.",
      overdoseEn: "Seek medical help in case of overdose.",
      overdoseAr: "اطلب المساعدة الطبية في حالة الجرعة الزائدة.",
      ingredientsEn: "Active ingredient info in English.",
      ingredientsAr: "مكونات الدواء باللغة العربية.",
      adImage: "https://cdn.example.com/image_50.jpg",
    }
    ]
  
async function main() {
    for (const product of initialProducts){
      await prisma.product.create({
        data: product,
      })
    }
}
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })